Repository cat-dev-group/bot, pull requests merged in 2021-04, with the labels that each got.

#5 Initial file structure
  .gitignore
  README.md
  bot/__init__.py
  bot/__main__.py
  bot/bot.py
  bot/constants.py
  bot/exts/__init__.py
  poetry.lock
  pyproject.toml
  tests/__init__.py
  tests/test_bot.py
Labels: good first issue

#4 Update README.md
  README.md
Labels: good first issue

#22 add yaml_parser capability
  bot/utilities/__init__.py
Labels: P1 - High Priority, enhancement

#23 change name of helper func
  bot/utilities/__init__.py
Labels: P2 - Medium Priority, enhancement

#21 Catification: Negative Replies
  bot/constants.py
  bot/exts/fun/catify.py
Labels: P2 - Medium Priority, enhancement

#54 Added `--help` command
  bot/bot.py
  bot/exts/fun/fun.py
  bot/exts/fun/makeembed.py
  bot/exts/fun/zencat.py
  bot/exts/moderation/moderation.py
  bot/exts/utilities/help.py
Labels: P1 - High Priority
